export const SkyblockArea = {
    "Hub": [
        "Archery Range",
        "Auction House",
        "Bank",
        "Bazaar Alley",
        "Blacksmith\'s House",
        "Builder\'s House",
        "Canvas Room",
        "Coal Mine",
        "Colosseum Arena",
        "Colosseum",
        "Community Center",
        "Election Room",
        "Farm",
        "Farmhouse",
        "Fashion Shop",
        "Fisherman\'s Hat",
        "Flower House",
        "Forest",
        "Graveyard",
        "Hexatorum",
        "High Level",
        "Library",
        "Mountain",
        "Museum",
        "Ruins",
        "Tavern",
        "Thaumaturgists",
        "Village",
        "Wilderness",
        "Wizard Tower"
    ],
    "The Park": [
        "Birch Park",
        "Dark Thicket",
        "Howling Cave",
        "Jungle Island",
        "Lonely Island",
        "Melody\'s Plateau",
        "Savanna Woodland",
        "Spruce Woods",
        "Viking Longhouse"
    ],
    "The Barn": [
        "The Barn",
        "Windmill"
    ],
    "Mushroom Desert": [
        "Desert Settlement",
        "Glowing Mushroom Cave",
        "Jake\'s House",
        "Mushroom Desert",
        "Mushroom Gorge",
        "Oasis",
        "Overgrown Mushroom Cave",
        "Shepherd\'s Keep",
        "Trapper\'s Den",
        "Treasure Hunter Camp"
    ],
    "Gold Mine": [
        "Gold Mine"
    ],
    "Deep Caverns": [
        "Diamond Reserve",
        "Gunpowder Mines",
        "Lapis Quarry",
        "Obsidian Sanctuary",
        "Pigmen\'s Den",
        "Slimehill"
    ],
    "Dwarven Mines": [
        "Aristocrat Passage",
        "Barracks of Heroes",
        "C&C Minecarts Co.",
        "Cliffside Veins",
        "Divan\'s Gateway",
        "Dwarven Mines",
        "Dwarven Tavern",
        "Dwarven Village",
        "Far Reserve",
        "Forge Basin",
        "Gates to the Mines",
        "Goblin Burrows",
        "Grand Library",
        "Great Ice Wall",
        "Hanging Court",
        "Lava Springs",
        "Miner\'s Guild",
        "Palace Bridge",
        "Rampart Quarry",
        "Royal Mines",
        "Royal Palace",
        "Royal Quarters",
        "The Forge",
        "The Lift",
        "The Mist",
        "Upper Mines"
    ],
    "Crystal Hollows": [
        "Crystal Hollows",
        "Crystal Nucleus",
        "Dragon\'s Lair",
        "Fairy Grotto",
        "Goblin Holdout",
        "Goblin Queen\'s Den",
        "Jungle Temple",
        "Jungle",
        "Khazad-dûm",
        "Lost Precursor City",
        "Magma Fields",
        "Mines of Divan",
        "Mithril Deposits",
        "Precursor Remnants"
    ],
    "Spider\'s Den": [
        "Spider\'s Den",
        "Arachne\'s Burrow",
        "Arachne\'s Sanctuary",
        "Archaeologist\'s Camp",
        "Grandma\'s House",
        "Gravel Mines",
        "Spider Mound"
    ],
    "The End": [
        "Dragon\'s Nest",
        "The End",
        "Void Sepulture",
        "Void Slate",
        "Zealot Bruiser Hideout"
    ],
    "Crimson Isle": [
        "Aura\'s Lab",
        "Barbarian Outpost",
        "Belly of the Beast",
        "Blazing Volcano",
        "Burning Desert",
        "Cathedral",
        "Chief\'s Hut",
        "Community Center",
        "Courtyard",
        "Crimson Fields",
        "Dojo",
        "Dragontail Auction House",
        "Dragontail Bank",
        "Dragontail Bazaar",
        "Dragontail Blacksmith",
        "Dragontail Minion Shop",
        "Dragontail Townsquare",
        "Dragontail",
        "Forgotten Skull",
        "Igrupan\'s Chicken Coop",
        "Igrupan\'s House",
        "Mage Council",
        "Mage Outpost",
        "Magma Chamber",
        "Matriarch\'s Lair",
        "Mystic Marsh",
        "Odger\'s Hut",
        "Plhlegblast Pool",
        "Ruins of Ashfang",
        "Scarleton Auction House",
        "Scarleton Bank",
        "Scarleton Bazaar",
        "Scarleton Blacksmith",
        "Scarleton Community Center",
        "Scarleton Minion Shop",
        "Scarleton Plaza",
        "Scarleton",
        "Smoldering Tomb",
        "Stronghold",
        "The Bastion",
        "The Dukedom",
        "The Wasteland",
        "Throne Room"
    ],
    "Winter Island": [
        "Einary\'s Emporium",
        "Gary\'s Shack",
        "Glacial Cave",
        "Hot Springs",
        "Jerry Pond",
        "Jerry\'s Workshop",
        "Mount Jerry",
        "Reflective Pond",
        "Sherry\'s Showroom",
        "Sunken Jerry Pond",
        "Terry\'s Shack"
    ],
    "Dungeon": [
        "Tha Catacombs (Entrance)",
        "The Catacombs (F1)",
        "The Catacombs (F2)",
        "The Catacombs (F3)",
        "The Catacombs (F4)",
        "The Catacombs (F5)",
        "The Catacombs (F6)",
        "The Catacombs (F7)",
        "The Catacombs (M1)",
        "The Catacombs (M2)",
        "The Catacombs (M3)",
        "The Catacombs (M4)",
        "The Catacombs (M5)",
        "The Catacombs (M6)",
        "The Catacombs (M7)",
        "Dungeon Hub"
    ],
    "Private Island": [
        "Private Island",
        "Your Island"
    ]
}